services:
  - type: web
    name: prahari-audit
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
